### ISSUE TITLE
Falsche Werte WW Temperatur

### ISSUE THREAD

**Issue by keldi23** [Trunks1982/Daikin-Rotex-HPSU-CAN#4]
In Regelmäßigen Abständen werden unplausible Werte der Warmwassertemperatur aufgenommen.
Durch diese wird der Temperaturverlauf im Home Assistant Diagramm nicht richtig dargestellt.

![Screenshot 2024-01-14 064657](https://github.com/Trunks1982/Daikin-Rotex-HPSU-CAN/assets/54002954/7b505837-6cd1-469f-bf4f-5c2a4d9f7964)

Als Lösung kann der Code folgendermaßen abgeändert werden:

#Warmwasser-Temperaturabfrage 
    - can_id: 0x180
      then:
        - lambda: |-
            if(x[0]==0xd2 and x[1]==0x00 and x[3]==0x00 and x[4] == 0x0e) {
              float temperature =float((float((int((x[6])+( (x[5])<<8))))/10));
              if(temperature < 100) {
                id(temperature_water).publish_state(temperature);
                ESP_LOGD("main", "Temperature received over can is %f", temperature);
              }
            }

**Comment by keldi23** [comment]
Das selbe bei TV und TVBH

**Comment by Trunks1982** [comment]
Nein bei mir läuft das einwandfrei.Da stimmt bei dir was nicht.Ich habe in keinem Wert unplausible Werte.

**Comment by keldi23** [comment]
Alles klar, ich weiß auch nicht warum. Vielleicht hängt das auch mit der WP Version zusammen oder so.
Ich lass die Änderung bei mir mal drin, dann siehts gut aus.

Auf jeden Fall vielen Dank für deine super Arbeit.

**Comment by Trunks1982** [comment]
An der WP Version sollte es nicht liegen.Hast du denn jetzt die neuste yaml mal installiert?
Was benutzt du für ein Kabel zum ESP?
Verdrillt?

Danke für dein Feedback.

**Comment by keldi23** [comment]
Ja, die neuste YAML hatte ich drauf.
Als Kabel habe ich nur ein Klingeldraht. Kann wirklich daran liegen. Da hast du recht.

**Comment by Trunks1982** [comment]
Ich benutze ein gedrilltes Lan Kabel. Wäre aufjedenfall nen Versuch wert.

**Comment by ap20132022** [comment]
bei mir kommt WW auch richtig an
