### ISSUE TITLE
Keine Daten mehr mit Version 1.3.7

### ISSUE THREAD

**Issue by ap20132022** [Trunks1982/Daikin-Rotex-HPSU-CAN#47]
Guten Morgen zusammen,
hab gestern die Version 1.3.7 aktualisiert.
Ich bekomme keine IST-Daten mehr angezeigt. Soll-Daten (z.B Warmwasser soll) funktioniert einwandfrei.
Woran kann es liegen?

**Comment by Trunks1982** [comment]
Schalter für Intervall Abfrage anschalten.

**Comment by ap20132022** [comment]
Hallo @Trunks1982 ,
vielen herzlichen Dank für deine schnelle Hilfe. 
Ja, es lag an den Schalter.

**Comment by ap20132022** [comment]
> Schalter für Intervall Abfrage anschalten.

warum hast du es standardmäßig "Off" programmiert? 
Ich würde nach Booten direkt "On" automatisch einschalten.

**Comment by Trunks1982** [comment]
Weil ich es sonst auch rausnehmen könnte.Das ist bewusst so gemacht.
