### ISSUE TITLE
Installationsprobleme bei Schritt 7

### ISSUE THREAD

**Issue by stasihasi** [Trunks1982/Daikin-Rotex-HPSU-CAN#48]
Hallo zusammen,

bin gerade dabei den ESP32 zu installieren. Die Schritte 1 bis 6 haben soweit auch gut funktioniert. Auch das Wlan Rotex Fallback Hotspot wird angezeigt und ich kann mich auch mit dem Passwort verbinden.

Jetzt zum Problem:
Leider öffnet sich aber nicht automatisch ein Browserfenster auf der ich mein WLAN eintragen kann.

Hoffe ihr könnt mir weiterhelfen!

Viele Grüße!

**Comment by MichaelGer1410** [comment]
Wenn du mit dem Hotspot verbunden bist, einfach mal http://192.168.4.1 in den brwoser eingeben.

**Comment by stasihasi** [comment]
ich bin geflasht von der schnellen Rückmeldung! 
Funktioniert! Am besten wird die Anleitung um die IP-Adresse ergänzt ;-)
Bin hoffentlich nicht der einzige, bei dem das passiert.

Vielen Dank nochmal!

**Comment by MichaelGer1410** [comment]
Hatte das Problem anfangs auch, daher der Tipp ;)
Schön das es bei dir Funktioniert!

**Comment by stasihasi** [comment]
Problem gelöst:
http://192.168.4.1/
