### ISSUE TITLE
Kühlbetrieb: keine Werte bei Umwaelzpumpe, Status Kompressor und Thermische Leistung

### ISSUE THREAD

**Issue by stasihasi** [Trunks1982/Daikin-Rotex-HPSU-CAN#49]
Hallo zusammen,

der ESP32 läuft soweit ganz gut seit ein paar Tagen. Was mir jedoch aufgefallen ist, dass beim Kühlbetrieb (andere Modi hab ich aufgrund der Jahreszeit noch nicht benutzt) für:
- Umwaelzpumpe (welche Pumpe ist gemeint, die für Trinkwasserzirkulation? Diese ist bei uns extern verbaut)
- Status Kompressor
- Thermische Leistung (liegt es hier am Kühlmodus selbst?)

keine Werte abgerufen werden.

Nachfolgend der entsprechende Screenshoot:
![Screenshoot_Kühlmodus](https://github.com/user-attachments/assets/8a254d18-52a6-41ef-8e21-fcaaedd4b262)

**Comment by Trunks1982** [comment]
Umwälzpumpe ist die intern verbaute.
Thermische Leistung beim Kühlen ist auf 0 gesetzt. Normal liegt der wert im Minus Bereich.
Status Kompressor ist beim Kühlen definitiv an. Ich hab aber eine Rotex HPSU Compact, da wird es unterstützt.

**Comment by stasihasi** [comment]
Die Bezeichnung des Innengeräts ist bei mir: Altherma 3 R ECH2O (EHSX08P50DA3)

Bzgl:
- Umwaelzpumpe: OK, also wie schon vermutet
- Status Kompressor: Schade dann, dass es bei meinem Modell anscheinend nicht funktioniert
- Thermische Leistung: also möchtest du nicht, dass der Wert negativ angezeigt wird und setzt ihn auf 0 wenn er negativ wird? Wäre halt ganz interessant für den Kühlbetrieb auch diese Info zu haben, aber ist auch nicht so tragisch.

**Comment by Trunks1982** [comment]
Kannst du gerne bei dir im code ändern wenn du möchtest.Vielleicht änder ich das auch wieder.Mal schaun

**Comment by stasihasi** [comment]
kannst du kurz beschreiben, wie ich das machen kann?

**Comment by Trunks1982** [comment]
der code müsste angepasst werden : - platform: template
    name: "Thermische Leistung"
    device_class: "power"
    unit_of_measurement: "kW"
    accuracy_decimals: 2
    update_interval: 10s
    lambda: |-
      if (id(text_betriebsart).state == "Warmwasserbereitung") {
        return ((id(TV).state - id(ruecklauf).state) * (4.19 * id(durchfluss).state)) / 3600;
      } else if (id(text_betriebsart).state == "Heizen") {
        return ((id(TVBH).state - id(ruecklauf).state) * (4.19 * id(durchfluss).state)) / 3600;
      } else {
        return 0.0;
      }

**Comment by Trunks1982** [comment]
> Die Bezeichnung des Innengeräts ist bei mir: Altherma 3 R ECH2O (EHSX08P50DA3)
> 
> Bzgl:
> 
> * Umwaelzpumpe: OK, also wie schon vermutet
> * Status Kompressor: Schade dann, dass es bei meinem Modell anscheinend nicht funktioniert
> * Thermische Leistung: also möchtest du nicht, dass der Wert negativ angezeigt wird und setzt ihn auf 0 wenn er negativ wird? Wäre halt ganz interessant für den Kühlbetrieb auch diese Info zu haben, aber ist auch nicht so tragisch.

Danke für deine Spende!👍

**Comment by stasihasi** [comment]
> der code müsste angepasst werden : - platform: template name: "Thermische Leistung" device_class: "power" unit_of_measurement: "kW" accuracy_decimals: 2 update_interval: 10s lambda: |- if (id(text_betriebsart).state == "Warmwasserbereitung") { return ((id(TV).state - id(ruecklauf).state) * (4.19 * id(durchfluss).state)) / 3600; } else if (id(text_betriebsart).state == "Heizen") { return ((id(TVBH).state - id(ruecklauf).state) * (4.19 * id(durchfluss).state)) / 3600; } else { return 0.0; }

Wo trage ich den Code ein, einfach in der configuration.yaml oder an einer anderen Stelle?

**Comment by Trunks1982** [comment]
Über das addon esphome.Da müsstest aber alles sehn vom code.

**Comment by stasihasi** [comment]
hab das ESPHome Add-on erst jetzt installiert. Der ESPHome war vorher und ist aktuell noch über die Integration mit HomeAssistant verbunden. Jetzt weiß ich aber nicht, wie ich einen fertig eingerichteten ESP nachträglich in das Add-on ESPHome bekomme, um mir dort dann den Code zu bearbeiten:
![grafik](https://github.com/user-attachments/assets/ba363590-9307-476d-a280-5729af36f49c)

**Comment by Trunks1982** [comment]
Erstellst einen neuen esp drin und kopierst vom github die yaml in den editor.Was vorher dein steht bitte rauslöschen.

**Comment by stasihasi** [comment]
ah ok, zerschieß ich mir dann das bisherige? Hab schon Automationen erstellt und würde ungern die ganze Arbeit nochmal machen wollen

**Comment by stasihasi** [comment]
ok danke!

**Comment by stasihasi** [comment]
So würde ich dann den Code anpassen, um die thermische Leistung im Kühlmodus zu erhalten:
- platform: template
    name: "Thermische Leistung"
    device_class: "power"
    unit_of_measurement: "kW"
    accuracy_decimals: 2
    update_interval: 10s
    lambda: |-
      if (id(text_betriebsart).state == "Warmwasserbereitung") {
        return ((id(TV).state - id(ruecklauf).state) * (4.19 * id(durchfluss).state)) / 3600;
      } else if (id(text_betriebsart).state == "Heizen") {
        return ((id(TVBH).state - id(ruecklauf).state) * (4.19 * id(durchfluss).state)) / 3600;
      } else {
        **return ((id(TVBH).state - id(ruecklauf).state) * (4.19 * id(durchfluss).state)) / 3600;
        #return 0.0;**
      }

Um die Anpassung wirksam zu machen, reicht nicht speichern zu klicken, sondern zusätzlich install:
Muss hier noch was beachtet werden, bevor install gekllickt wird, oder geht das einfach im laufenden Betrieb?
![grafik](https://github.com/user-attachments/assets/fe6b7a66-4fd3-4b94-966a-192603662e76)

**Comment by Trunks1982** [comment]
Dein code ist falsch.Guck mal hin

**Comment by stasihasi** [comment]
also ich will haben, dass die Leistung negativ ist!
dachte ich muss die gleiche formel wie beim heizen nehmen und dann wirds beim Kühlen einfach negativ.

**Comment by stasihasi** [comment]
![grafik](https://github.com/user-attachments/assets/b802a02b-af37-4b3c-b9aa-bc029c1273ea)

geht 2x "else if" hintereinander?

**Comment by Trunks1982** [comment]
Joa.Siehst ja auch weiter oben im code zb.
Sieht schon besser aus.Kannst ja so mal testen.

**Comment by Trunks1982** [comment]
Und hats geklappt?

**Comment by stasihasi** [comment]
mit der Hilfe von dir natürlich ;-)

![grafik](https://github.com/user-attachments/assets/5224acba-6af9-4e62-a346-aaf74a18bda4)

Danke nochmal!

**Comment by Trunks1982** [comment]
👍
